name: Browserstack Tests
on: [push]
jobs:
    build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
              java-version: 1.8
        - name: Setup VM
          run: |
              export CHROME_BIN=/usr/bin/google-chrome
              export DISPLAY=:99.0
              sudo apt-get update
              sudo apt-get install dbus-x11
              sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
              sudo apt-get install -y libappindicator1 fonts-liberation firefox
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
              sudo dpkg -i google-chrome*.deb
              wget https://iridium-cloud-support.s3.amazonaws.com/opera-stable_62.0.3331.116_amd64.deb
              sudo dpkg -i opera-*.deb
              mkdir ~/.ssh
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              gpg -q --batch --yes --decrypt --passphrase="${{ secrets.gpgEncryptedFilePassword }}" -o secring-iridium.gpg secring-iridium.gpg.gpg
              gpg -q --batch --yes --decrypt --passphrase="${{ secrets.gpgEncryptedFilePassword }}" -o ~/.ssh/id_rsa id_rsa.gpg
              chmod 600 ~/.ssh/id_rsa
              eval `ssh-agent -s`
              ssh-add ~/.ssh/id_rsa
              git config --global user.email "matthewcasperson@gmail.com"
              git config --global user.name "Matthew Casperson"
        - name: Build with Gradle
          run: ./gradlew build -x test
          env:
              ossrhPassword: ${{ secrets.ossrhPassword }}
              ossrhUsername: ${{ secrets.ossrhUsername }}
              DisableSigning: true
    - name: Run iPhone tests
          run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
          env:
              TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'iPhone'}"
              ossrhPassword: ${{ secrets.ossrhPassword }}
              ossrhUsername: ${{ secrets.ossrhUsername }}
              DisableSigning: true
              browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
              browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run iPod tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'iPad'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Safari tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'Safari'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Android tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'Android'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run IE tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'IE','additionalTags':'~@iefail'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Edge tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'Edge'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
