name: Java CI
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup VM
      run: |
        export CHROME_BIN=/usr/bin/google-chrome
        export DISPLAY=:99.0
        sudo apt-get update
        sudo apt-get install dbus-x11
        sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
        sudo apt-get install -y libappindicator1 fonts-liberation firefox
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome*.deb
        wget https://iridium-cloud-support.s3.amazonaws.com/opera-stable_62.0.3331.116_amd64.deb
        sudo dpkg -i opera-*.deb
        mkdir ~/.ssh
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        gpg -q --batch --yes --decrypt --passphrase="${{ secrets.gpgEncryptedFilePassword }}" -o secring-iridium.gpg secring-iridium.gpg.gpg
        gpg -q --batch --yes --decrypt --passphrase="${{ secrets.gpgEncryptedFilePassword }}" -o ~/.ssh/id_rsa id_rsa.gpg
        chmod 600 ~/.ssh/id_rsa
        eval `ssh-agent -s`
        ssh-add ~/.ssh/id_rsa
        git config --global user.email "matthewcasperson@gmail.com"
        git config --global user.name "Matthew Casperson"
    - name: Build with Gradle
      run: ./gradlew build -x test
      env:
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
    - name: Update Docs
      run: |
          git clone git@github.com:mcasperson/mcasperson.github.io.git
          cd mcasperson.github.io
          rm -rf IridiumApplicationTesting/javadoc
          cp -r ../build/docs/javadoc IridiumApplicationTesting
          git add .
          git commit -m "Updated docs"
          git push origin master
    - name: Run Phantom JS Tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
        TEST_SUITE: "{'browsers':['PhantomJS'],'runNegTests':true,'runSimpleTests':true}"
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
    - name: Run Chrome Headless tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
        TEST_SUITE: "{'browsers':['ChromeHeadless'],'runNegTests':false,'runSimpleTests':false}"
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
        browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
        browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Firefox tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
        TEST_SUITE: "{'browsers':['Marionette'],'runNegTests':false,'runSimpleTests':false}"
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
        browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
        browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Firefox Headless tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
        TEST_SUITE: "{'browsers':['FirefoxHeadless'],'runNegTests':false,'runSimpleTests':false}"
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
        browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
        browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Opera tests
      run: ./gradlew test -Dopera.binary=/usr/bin/opera -DtestBrowsers=${TEST_SUITE}
      env:
        TEST_SUITE: "{'browsers':['Opera'],'runNegTests':false,'runSimpleTests':false}"
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
        browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
        browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run iPhone tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'iPhone'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run iPod tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'iPad'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Safari tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'Safari'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Android tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'Android'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run IE tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'IE','additionalTags':'~@iefail'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Run Edge tests
      run: ./gradlew test -DtestBrowsers=${TEST_SUITE}
      env:
          TEST_SUITE: "{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'Edge'}"
          ossrhPassword: ${{ secrets.ossrhPassword }}
          ossrhUsername: ${{ secrets.ossrhUsername }}
          DisableSigning: true
          browserStackAccessToken: ${{ secrets.browserStackAccessToken }}
          browserStackUsername: ${{ secrets.browserStackUsername }}
    - name: Publish
      run: >
        ./gradlew
        -DisableSigning=false
        -Psigning.keyId=${{ secrets.gpgKeyId }}
        -Psigning.password=${{ secrets.gpgKeyPassword }}
        -Psigning.secretKeyRingFile=secring-iridium.gpg
        -PMavenVersion=0.0.0-SNAPSHOT
        uploadArchives
      env:
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
